config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    resources :servicios do
      resources :subservicios
    end
  end

   root 'statics#index'

   get 'servicios' => 'statics#services'

   get 'servicios/:id' => 'statics#services'
   
   
   get 'servicios/:id/subservicios/:subservicio_id' => 'statics#services'

   get 'sectores' => 'statics#sectors'

   get 'sectores/:id' => 'statics#sectors'

   get 'equipo' => 'statics#team'

   get 'contacto' => 'statics#contact'

   post 'contacto' => 'statics#contact_new'

   get 'publicaciones' => 'statics#publications'

   get 'publicaciones/:id' => 'statics#showPublication', :as => :publicacion

   get 'nosotros' => 'statics#our'

   get 'suscribir' => 'statics#subscribe'

   post 'suscribir' => 'statics#subscribe_new'

   get 'postular' => 'statics#postulate'

   post 'postular' => 'statics#postulate_new'

   get 'recursos' => 'statics#resources'

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only:[:subscribe_new,:postulate_new]

  before_action :set_sector, only:[:sectors]
  before_action :set_service, only:[:services]
  before_action :set_publications, only:[:publications]
  before_action :susbcriptor_params, only:[:subscribe_new]
  before_action :postulate_params, only:[:postulate_new]
  before_action :contact_params, only:[:contact_new]
  before_action :set_locale

 
  def set_locale
    I18n.locale = :es || I18n.default_locale
  end

  def index
    @subservicios=Subservicio.where(estado:true)
    
  end

  def services
  end

  def sectors
    @sectores=Sectore.where(estado: true).order(nombre: :asc)
  end

  def team
    @roles=Role.all.order(nombre: :asc)
    @equipo=Equipo.where(estado:true).order(apellidos: :asc)
    respond_to do |format|
      format.html
      format.json { render :json => {:roles => @roles,:equipo => @equipo}}
    end
  end

  def subscribe
  end

  def subscribe_new
    @suscriptor=Inscrito.new(susbcriptor_params)
    if @suscriptor.save
      @suscriptor=Inscrito.new
      flash.now[:correcto]="Te has suscrito correctamente, te enviaremos un mensaje a tu correo."
      render :subscribe
    else
      flash.now[:errors]=@suscriptor.errors
      render :subscribe
    end
  end

  def contact
    @contacto=Contacto.new
  end

  def contact_new
    @contacto=Contacto.new(contact_params)
    if @contacto.save
      @contacto=Contacto.new
      flash.now[:correcto]="Tu mensaje ha sido enviado correctamente, pronto nos comunicaremos contigo."
      render :contact
    else
      flash.now[:errors]=@contacto.errors
      render :contact
    end
    
  end

  def publications
    @categorias=Category.all
  end

  def showPublication
    @categorias=Category.all

    if params[:id].present?
      @publicacion_actual=Post.includes(:category,:equipo).find(params[:id])
    end
  end

  def our
  end

  def postulate
  end

  def postulate_new
    @postulante=Postulante.new(postulate_params)
    if @postulante.save
      @postulante=Contacto.new
      flash.now[:correcto]="Tu postulación se ha procesado correctamente, la revisaremos."
      render :postulate
    else
      flash.now[:errors]=@postulante.errors
      render :postulate
    end
  end

  def resources
    servicios=Servicio.where(estado:true).order(nombre: :asc)
    recursos=Recurso.where(estado:true).order(created_at: :asc)
    respond_to do |format|
      format.html
      format.json {render :json => {:servicios => servicios, :recursos => recursos }}
    end
  end

  def set_sector
    if(params[:id].present?)
      @sector_actual=Sectore.find(params[:id])

    else
      @sector_actual=Sectore.where(estado:true).order(nombre: :asc).first
    end

  end

  def set_service

    #si existe el parametro servicio
    if(params[:id].present?)
      @servicio_actual=Servicio.includes(:subservicios).find_by(id:params[:id], estado:true)
    
    else
      @servicio_actual=Servicio.includes(:subservicios).where(estado:true).order(nombre: :asc).first
    end
  end


  def set_publications
    pagina=1
    if params[:page].present?
      pagina=params[:page]
    else
      pagina=1
    end

    if(params[:query].present? and params[:category].present?)
      @publicaciones=Post.where(" estado=true and titulo LIKE ? and category_id= ?","%#{params[:query]}%", params[:category]).order(created_at: :desc).page(pagina).per_page(5)
    
    elsif (!params[:query].present? and params[:category].present?)
      @publicaciones=Post.where(" estado=true and category_id= ?", params[:category]).order(created_at: :desc).page(pagina).per_page(5)
    
    elsif (params[:query].present? and !params[:category].present?)
      @publicaciones=Post.where(" estado=true and titulo LIKE ? ","%#{params[:query]}%").order(created_at: :desc).page(pagina).per_page(5)
    else
      @publicaciones=Post.includes(:category).where(estado:true).order(created_at: :desc).page(pagina).per_page(5)
    end
  end

  def susbcriptor_params
    params.permit(:nombre,:email)
  end

  def postulate_params
    params.permit(:nombres,:email,:cv)
  end

  def contact_params
    params.require(:contacto).permit(:nombres,:email,:telefono,:mensaje)
  end


end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/contact.html.erb
<div class="contacto-page">
	<div class="ed-container full" style="position: relative;justify-content: center;">
			<div style="background:url(<%=asset_path 'contacto.jpg'%>);background-size:cover;background-position: center;" class="v-contacto-img"></div>
			<div class="v-contacto-opacidad"></div>
		<div class="v-contacto">
			<div class="ed-container">
				<div class="ed-item s-100">
					<h1 class="v-contacto-titulo">Contacto</h1>
				</div>
			</div>
			<div class="ed-container main-center" style="background-color: #fff;margin-top: auto;z-index: 30">
				<div class="ed-item s-100 l-95" style="	height: 35px;z-index: 100;">
					
				</div>
			</div>
		</div>
	</div>

	<div class="ed-container informacion">
		<div class="ed-item s-100 l-50 informacion-izquierda">
			<h3 class="informacion-titulo">Como encontrarnos</h3>
			<p class="informacion-texto">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium rerum sit unde sed, nam facere molestiae provident veritatis?</p>
			<div class="datos">
				<span class="datos-titulo">Oficina Central</span>
				<p class="datos-direccion  icon-ubicacion">Calle las Dalias D1-5 Interior 101 Urb. Miiraflores</p>
				<p class="datos-telefono icon-phone"><span class="datos-atributo">Telefono: </span>968499806 / (RPM) *186163</p>
				<p class="datos-email icon-email"><span class="datos-atributo">Email:</span> williarhidalgo@gmail.com</p>
			</div>
		</div>
		<div class="ed-item s-100 l-50 no-padding informacion-derecha">
			<div class="ed-item s-100 " style="background: #fff;">
					<%if flash[:correcto]%>
						<div class="notificacion ">
							<div class="notificacion-cerrar">x</div>
							<p class="notificacion-texto"><%=flash[:correcto]%></p>
						</div>
					<%elsif flash[:errors]%>
						<div class="notificacion">
							<div class="notificacion-cerrar">x</div>
							<p class="notificacion-texto">No se pudo enviar el mensaje, por favor corrige los siguientes problemas:</p>
							<ul class="notificacion-lista">
								<% flash[:errors].each do |key, value| %>
									<li class="notificacion-item"><span class="notificacion-clave"><%=key%></span> - <%=value%></li>
								<% end %>
							</ul>
						</div>
					<%end%>
			</div>
			<div class="ed-item s-100">
				<h3 class="informacion-titulo">Envianos un mensaje</h3>
			</div>
			<%=form_for @contacto, url: contacto_path, html: { class: "informacion-formulario ed-container ed-item"} do |f|%>
				<div class=" ed-item s-100 formulario-caja">
					<label for="" class="formulario-label">Nombre Completo</label>
					<%=f.text_field :nombres,{class:"formulario-text",placeholder:"Nombre Completo"}%>
				</div>
				<div class=" ed-item s-100 l-50 formulario-caja">
					<label for="" class="formulario-label">Email</label>
					<%=f.email_field :email,{class:"formulario-text",placeholder:"Email"}%>
				</div>
				<div class=" ed-item s-100 l-50 formulario-caja">
					<label for="" class="formulario-label">Telefono/Celular</label>
					<%=f.text_field :telefono,{class:"formulario-text",placeholder:"Telefono/Celular"}%>
				</div>
				<div class=" ed-item s-100 formulario-caja">
					<label for="" class="formulario-label">Mensaje</label>

					<%=f.text_area :mensaje,{class:"formulario-textarea",placeholder:"Mensaje",rows:"10"}%>
				</div>
				<div class="formulario-caja ed-item s-100">
				<button class="btn btn-4" style="color:red"><span>Enviar</span></button>
				</div>
			<%end%>
		</div>
	</div>

	<div class="ed-container full">
		<div class="mapa-google" id="mapa-google">
			
		</div>
	</div>
</div>
<%=javascript_include_tag "contacto.js"%>

app/views/statics/index.html.erb
<div class="ed-container full index">
		<div class="ed-item s-100 ed-container full banner " style="height: 70vh">
			<div class="banner-fondo" style="background:url(<%=asset_path 'img-header.jpg'%>);background-size:cover;background-position:top center;background-attachment: scroll">
				
			</div>
			<div class="banner-opacidad"></div>
			<div class=" ed-item s-100 m-80 l-70 xl-100 banner-contenedor-texto">
				<h2 class="banner-titulo">Esta es una frase increible</h2>
				<h1 class="banner-subtitulo">Esta es un caracteristica importante</h1>
			</div>
			<div class="ed-item s-100 banner-contenedor-btn">
				<a href="/contacto" class="btn banner-btn btn-4 "><span>Contáctanos</span></a>
			</div>
		</div>
		
		<%if !@servicios_global.nil?%>
		<div class="ed-item s-100 ed-container full servicios-contenedor abcenter ">
			<div class="ed-item s-100 m-90 l-70 xl-60">
				<h3 class="servicios-titulo">Servicios</h3>
			</div>
				<div class="ed-item s-100 m-90 l-70 xl-60 servicios">
					
					<%@servicios_global.each do |servicio|%>
						<div class="servicio-item abcenter">
							<div class="servicio-fondo" style="background:url(<%=servicio.imagen_url%>);background-size:50%;background-position:top center;background-attachment: scroll;"">
							</div>
							<div class="servicio-opacidad">
							</div>
							<h4 class="servicio-texto"><%=servicio.nombre%></h4>
							<% subservicios_coincidentes=@subservicios.select{|item| item.servicio_id== servicio.id }%>
							<%if subservicios_coincidentes.size>0%>
								<ul class="servicio-lista">
									<%subservicios_coincidentes.each do |subservicio| %>
										<li class="servicio-lista-item">
											<a href="/servicios/<%=servicio.id%>/subservicios/<%=subservicio.id%>" class="servicio-lista-link"><%= subservicio.nombre%></a>
										</li>
									<%end%>
								</ul>
							<%end%>
						</div>
					<%end%>
			</div>
			</div><!--AQUI AGREGUE UN DIV-->
			<%end%>

		<div class="ed-item s-100 ed-container full empresas-contenedor abcenter ">
			<div class="ed-item s-100 m-90 l-70 xl-60 empresas slick-parent-empresas">
				<div class="empresa-contenedor">
					<span></span>
					<img src=<%=asset_path 'logo-uno.jpg'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
					<span></span>
					<img src=<%=asset_path 'logo-dos.jpg'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
					<span></span>
					<img src=<%=asset_path 'logo-tres.png'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
					<span></span>
					<img src=<%=asset_path 'logo-cuatro.jpg'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
					<span></span>
					<img src=<%=asset_path 'logo-cinco.jpg'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
					<span></span>
					<img src=<%=asset_path 'logo-seis.png'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
				<span></span>
					<img src=<%=asset_path 'logo-siete.jpg'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
				<span></span>
					<img src=<%=asset_path 'logo-ocho.jpg'%> alt="" class="empresa-img">
				</div>

				<div class="empresa-contenedor">
				<span></span>
					<img src=<%=asset_path 'logo-nueve.png'%> alt="" class="empresa-img">
				</div>
			</div>
		</div>
		
		<div class="ed-item s-100 ed-container full anuncios abcenter ">
			<div class="ed-item s-100 m-90 l-70 xl-60 ed-container anuncios-contenedor ">
				<div class="ed-item s-100 m-100 l-2-3 ">
					<div class="anuncios-cabecera">
						<h2 class="anuncios-cabecera-titulo">Publicaciones</h2>
						<h3 class="anuncios-cabecera-parrafo">Aqui debe encontrarse algun texto realcionado a los anuncios que encuentra el visitantte</h3>
						<a href="/publicaciones" class="anuncios-cabecera-link">Ver más</a>
					</div>
				</div>
			<%@publicaciones_global.each do |pub|%>
				<div class="ed-item s-100 m-50 l-1-3 " >
					<div class="anuncio">
						<div class="anuncio-cabeza">
							<a class="anuncio-imagen" href="/publicaciones/<%=pub.id%>" style="background: url(<%=pub.imagen_url%>);background-size:cover;background-position:center;"></a>
							<span class="anuncio-categoria"><%=pub.category.nombre%></span>
						</div>
						<div class="anuncio-cuerpo">
							<h4 class="anuncio-titulo"><a href="/publicaciones/<%=pub.id%>"><%=pub.titulo.mb_chars.limit(70).to_s%></a></h4>
							<span class="anuncio-fecha"><%= l(pub.created_at,format: :medium)%></span>
						</div>
					</div>
				</div>
			<%end%>
				
			</div>
		</div>
</div>

app/views/statics/our.html.erb
<div class="nosotros-page">
	<div class="ed-container full" style="position: relative;justify-content: center;">
			<div style="background:url(<%=asset_path 'publicacion.jpg'%>);background-size:cover;background-position: center;" class="v-nosotros-img"></div>
			<div class="v-nosotros-opacidad"></div>
		<div class="v-nosotros">
			<div class="ed-container">
				<div class="ed-item s-100">
					<h1 class="v-nosotros-titulo">Nuestra Empresa</h1>
				</div>
			</div>
			<div class="ed-container main-center" style="background-color: #fff;margin-top: auto;z-index: 30">
				<div class="ed-item s-100 l-95" style="	height: 35px;z-index: 100;">
					
				</div>
			</div>
		</div>
	</div>

	<div class="ed-container ">
		

	</div>

	
</div>

app/views/statics/postulate.html.erb
<div class="postular-page ">
	<div class="ed-container full" style="position: relative;justify-content: center;">
		<div style="background:url(<%=asset_path 'postular.jpg'%>);background-size:cover;background-position: center;" class="v-postular-img"></div>
		<div class="v-postular-opacidad"></div>
		<div class="v-postular">
			<div class="ed-container">
				<div class="ed-item s-100">
					<h1 class="v-postular-titulo">Postula</h1>
				</div>
			</div>
		</div>
	</div>
	<div class="ed-container postular  ">

		<div class="ed-item s-100 m-70 l-40 ">
			<div class="postular-formulario">
				<div class="postular-header">
					<h2 class="postular-titulo">postular</h2>
					<p class="postular-subtitulo">Sube tu curriculum aquí</p>
				</div>
				<div class="postular-body">
					<form action="/postular" method="POST" enctype="multipart/form-data" class="formulario">
						<input type="text" name="nombres" placeholder="Tu nombre completo" class="postular-nombres formulario-text">
						<input type="text" class="postular-input formulario-text" name="email" placeholder="Ingresa tu correo" />
						<div class="formulario-file">
						  <span class="formulario-file-span" id="cv-nombre-archivo">Selecciona tu archivo</span>
						    <label for="cv" class="formulario-file-label">Cargar<input type="file" id="cv" name="cv" class="formulario-file-input"></label>
						</div>
						<button class="postular-btn btn " value="">postularme</button>
					</form>
				</div>
			</div>
		</div>
		<div class="ed-item s-100 m-100 l-55 " style="background: #fff;">
			<div style="background: #fff;">
					<%if flash[:correcto]%>
						<div class="notificacion ">
							<div class="notificacion-cerrar">x</div>
							<p class="notificacion-texto"><%=flash[:correcto]%></p>
						</div>
					<%elsif flash[:errors]%>
						<div class="notificacion">
							<div class="notificacion-cerrar">x</div>
							<p class="notificacion-texto">No se pudo enviar el mensaje, por favor corrige los siguientes problemas:</p>
							<ul class="notificacion-lista">
								<% flash[:errors].each do |key, value| %>
									<li class="notificacion-item"><span class="notificacion-clave"><%=key%></span> - <%=value%></li>
								<% end %>
							</ul>
						</div>
					<%end%>
			</div>
			<div class="postular-informacion">
			<h2 class="postular-informacion_titulo">Necesitamos profesionales como tú</h2>
				<p class="postular-informacion_texto">Constantemente estamos en busca de <strong>nuevos talentos</strong> para integrar a nuestro staff.</p>
				<p class="postular-informacion_texto-dos">Si consideras que tus habilidades se ajustan a los servicios que brindamos, no dudes <strong>postular</strong> y <strong>dejarnos tu CV</strong>.</p>
				<span class="postular-informacion_firma">Economistas Asociados</span>
			</div>
		</div>
	</div>
</div>

app/views/statics/publications.html.erb
<div class="publicacion-page">
	<div class="ed-container full" style="position: relative;justify-content: center;">
			<!--<div style="background:url(<%=asset_path 'publicacion.jpg'%>);background-size:cover;background-position: center;" class="v-publicacion-img"></div>-->
			<div class="v-publicacion-opacidad"></div>
		<div class="v-publicacion">
			<div class="ed-container">
				<div class="ed-item s-100">
					<h1 class="v-publicacion-titulo">Publicaciones</h1>
				</div>
			</div>
			<!--<div class="ed-container main-center" style="background-color: #fff;margin-top: auto;z-index: 30">
				<div class="ed-item s-100 l-95" style="	height: 35px;z-index: 100;">
					
				</div>
			</div>-->
		</div>
	</div>

	<div class="ed-container ">
		<div class="ed-container ed-item s-100  cross-center busqueda ">
			<form action="/publicaciones" method="get">
				<h2 class="busqueda-titulo">Busqueda</h2>
				<input type="text" name="query" class="formulario-text busqueda-filtro" placeholder="Ingresa un texto que buscar" style="margin-right: 1em;" value="<%=params[:query]%>">
				
				<div class="select select-m busqueda-combo ">
				    <span class="arr"></span>
				    <%=select_tag "category", options_from_collection_for_select(@categorias, "id", "nombre",:selected => params[:category]),prompt:'Selecciona Categoria'%>
				</div>
				<input type="submit" class="btn busqueda-boton" value="Buscar">
			</form>
		</div>


		<div class="ed-item s-100 l-65 no-padding">
			<div class="publicaciones">
				<%if !@publicaciones.empty? %>
				<%= paginate(@publicaciones)%>
					<%@publicaciones.each do |pub|%>
						<div class="publicacion">
							<div class="publicacion-imagen" style="background: url(<%=pub.imagen_url%>);background-size:cover;background-position: center;">
								<a href="/publicaciones/<%=pub.id%>" class="publicacion-enlace"></a>
								<span class="publicacion-categoria"><%=pub.category.nombre%></span>
							</div>
							<div class="publicacion-contenido">
								<a href="/publicaciones/<%=pub.id%>" class="publicacion-titulo"><%=pub.titulo%></a>
								<strong class="publicacion-fecha"><%= l(pub.created_at,format: :long)%></strong>
								<div class="publicacion-texto"><%= raw(pub.contenido.mb_chars.limit(200).to_s)%></div>
							</div>
						</div>
					<%end%>
					<%= paginate(@publicaciones)%>
				<%else%>
				<p>No se encontraron coincidencias!</p>
				<%end%>

			</div>
		</div>

		<div class="ed-item s-100 l-35">
			<div class="contacto">
				<h2 class="contacto-titulo">¿Necesitas más información?</h2>
				<div class="enlaces">
					<a href="/contacto" class="enlace">
						<span class="enlace-titulo">Ubicanos</span>
						<p class="enlace-texto">Todo lo que necesitas saber de los lideres en la industria </p>
					</a>

					<a href="/recursos" class="enlace">
						<span class="enlace-titulo">Desarrolla tu Talento</span>
						<p class="enlace-texto">Los temas de materia institucional 100% disponibles</p>
					</a>

					<a href="/suscribir" class="enlace">
						<span class="enlace-titulo">Entérate</span>
						<p class="enlace-texto">Nuestras publicaciones en tu bandeja de email a un solo click</p>
					</a>

					<a href="/postular" class="enlace">
						<span class="enlace-titulo">Postula</span>
						<p class="enlace-texto">Nuestro staff necesita talentos como tú</p>
					</a>
				</div>
			</div>
			
		</div>
		</div>

	
</div>

app/views/statics/resources.html.erb
<script type="text/template" id="recurso_item-temp">
	<div class="recurso-item">
		<h3 class="recurso-nombre">{{recurso.titulo}} - <a class="recurso-archivo" target="_blank" :href="recurso.archivo.url">Descargar</a></h3>
		<span class="recurso-span">Enlaces relacionados</span>
		<div class="recurso-links" v-html="recurso.links"></div>
	</div>
</script>

<div class="recurso-page" id="recurso-page">
	<div class="ed-container full" style="position: relative;justify-content: center;">
			<div style="background:url(<%=asset_path 'recursos.jpg'%>);background-size:cover;background-position: center;" class="v-recurso-img"></div>
			<div class="v-recurso-opacidad"></div>
		<div class="v-recurso">
			<div class="ed-container">
				<div class="ed-item s-100">
					<h1 class="v-recurso-titulo">Desarrolla tu talento</h1>
					
				</div>
			</div>
			<div class="ed-container main-center" style="background-color: #fff;margin-top: auto;z-index: 30">
				<div class="ed-item s-100 l-95" style="	height: 35px;z-index: 100;">
					
				</div>
			</div>
		</div>
	</div>
		
		
		<div class="ed-container v-recurso-contenido ">
			<div class="ed-item s-100 l-70" style="margin:auto;">
				<p style="font-size: 1.1em;text-align: center;">Aquí encontrarás documentos y enlaces de inteŕes relacionados con los servicios que brindamos en la empresa, estos recursos te servirán para informate y capacitarte en cada una de nuestras especialidades, son totalmente gratuitos.</p>
			</div>
			<div class="ed-item s-100 l-100 ">
				<div class="v-recurso-filtrado ed-container">
					<div class="ed-item s-100 main-end">
						<div class="select select-m v-recurso-filtrado-select">
					    <span class="arr"></span>
					    <select name="" id="" v-model="servicio_seleccionado">
					    	<option value="">Selecciona una opción</option>
					    	<option v-for="servicio in servicios" :value="servicio">{{servicio.nombre}}</option>
					    </select>
					  </div>
					</div>
				</div>
			</div>
			<div class="ed-item s-100 l-70" style="margin:auto">
				<div class="recursos">
					<recurso-item v-for="recurso in recursos" :recurso="recurso"></recurso-item>
					
				</div>
			</div>
	</div>
</div>

app/views/statics/sectors.html.erb
<div class="servicios-page ">
	<div class="ed-container full" style="position: relative;justify-content: center;">
		<%if !@sector_actual.nil?%>
			<div style="background:url(<%=(@sector_actual.imagen_url)%>);background-size:cover;background-position: center;" class="v-subservicio-img"></div>
		<%end%>
		<div class="v-subservicio-opacidad"></div>
		<div class="v-subservicio">
			<h1 class="v-subservicio-titulo">
				<%if !@sector_actual.nil?%>
					<%=@sector_actual.nombre%>
				<%end%>
			</h1>
			<div class="ed-container main-center" style="background-color: #fff;margin-top: auto;z-index: 30">
				<div class="ed-item s-100 l-95" style="	height: 35px;z-index: 100;"></div>
			</div>
		</div>
	</div>
	<div class="ed-container v-sector-contenido ">
		<div class="ed-item s-100 l-70 ">
			<%if !@sector_actual.nil?%>
				<h2 class="v-sector-segundo-titulo">
						<%=@sector_actual.nombre%>
				</h2>
				<div class="v-sector-texto" style="margin-top: 0;">
					<%=raw(@sector_actual.descripcion)%>
				</div>
			<%end%>
		</div>
		<div class="ed-item s-100 l-30" style="border-left: rgba(221, 221, 221, 0.2) solid 2px;margin-top: 1em;}">
			<div class="v-sector-menu-vertical">
				<h3 class="v-sector-menu-vertical-cabecera">Sectores</h3>
				<ul class="v-sector-menu-vertical-lista" id="vMenu-servicios">
					<%@sectores.each do |sector|%>
						<li class="v-sector-menu-vertical-item"><a href="/sectores/<%=sector.id%>" class="v-sector-menu-vertical-link"><%=sector.nombre%></a></li>
					<%end%>
					<!--
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Agua y saneamiento</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Comercio</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Construcción e infraestructura de transporte</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Energía e hidrocarburos</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Sistema financiero, previsional y seguros</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Manufactura</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Minería</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Sector público</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Telecomunicaciones</a></li>
					<li class="v-sector-menu-vertical-item"><a href="#" class="v-sector-menu-vertical-link">Otros sectores</a></li>-->
				</ul>
			</div>
		</div>
	</div>
</div>